#!name=🅼🅾🅳🆂🅷🆄🅱
#!desc=多功能转换模块，编辑参数以使用
#!arguments=Script-Hub:true, Cuttle-Fish:true, Plugin-Hub:http, 资源网站策略:随机节点
#!arguments-desc=🔘Script-Hub\n\n· 默认启用，若禁用则下方设置无效\n\n🔘 Cuttle-Fish\n\n· 墨鱼手记网页变身，默认启用\n\n🔘 Plugin-Hub\n\n· 可莉插件中心变身，默认启用，填入 # 可禁用\n\n🔘 资源网站策略\n\n· 默认使用模块内置随机节点代理分组以免下载受限
# 整理作者：LOWERTOP
# 仓库地址：https://github.com/LOWERTOP/Shadowrocket-First

[General]
# Script Hub
force-http-engine-hosts = %APPEND% script.hub, *.script.hub

[Rule]
# Cuttle-Fish QUIC BLOCK
AND,((DOMAIN-SUFFIX,ddgksf2013.top),(PROTOCOL,QUIC)),REJECT-NO-DROP
# 代理规则
DOMAIN-SUFFIX,kelee.one,{{{资源网站策略}}}
DOMAIN-SUFFIX,ddgksf2013.top,{{{资源网站策略}}}

[Proxy Group]
随机节点 = url-test,url=http://www.gstatic.com/generate_204,interval=180,tolerance=0,timeout=3,select=0,policy-regex-filter=.*

[Header Rewrite]
# PluginHub @iab0x00
{{{Plugin-Hub}}}-request ^https://hub\.kelee\.one/list\.json header-del if-none-match

[Body Rewrite]
# PluginHub @iab0x00
{{{Plugin-Hub}}}-response ^https://hub\.kelee\.one/list\.json "loon://import\?plugin=(https://kelee.one/Tool/Loon/Lpx/(.+).lpx)" "shadowrocket://install?module=http://script.hub/file/_start_/$1/_end_/$2.sgmodule%3Ftype%3Dloon-plugin%26target%3Dshadowrocket-module%26del%3Dtrue%26jqEnabled%3Dtrue"

[Script]
# Script Hub
Script Hub: 前端 = type=http-request, pattern=^https?:\/\/script\.hub\/($|edit\/|reload), script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/script-hub.js, timeout=300, enable={{{Script-Hub}}}
Script Hub: 重写转换 = type=http-request, pattern=^https?:\/\/script\.hub\/file\/_start_\/.+type=(?:qx-rewrite|surge-module|loon-plugin|all-module), script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/Rewrite-Parser.js, timeout=300, enable={{{Script-Hub}}}
Script Hub: 规则集转换 = type=http-request, pattern=^https?:\/\/script\.hub\/file\/_start_\/.+type=rule-set, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/rule-parser.js, timeout=300, enable={{{Script-Hub}}}
Script Hub: 脚本转换 = type=http-request, pattern=^https?:\/\/script\.hub\/convert\/, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/script-converter.js, timeout=300, enable={{{Script-Hub}}}

# Cuttle-Fish
网页变身 = type=http-response, pattern=^https?:\/\/ddgksf2013.top\/$,requires-body=1,max-size=-1,script-path=https://ddgksf2013.top/scripts/web.rocket.js,enable={{{Cuttle-Fish}}}, timeout=3500

[MITM]
hostname = %APPEND% script.hub, *.script.hub, hub.kelee.one, ddgksf2013.top
